import type { AppList } from './interface';

/**
 * 模拟数据
 */
export const MOCK_APP_LIST: AppList = [
    { id: 1, name: 'app_1', icon: '' },
    { id: 2, name: 'app_2', icon: '' },
    { id: 3, name: 'app_3', icon: '' },
    { id: 4, name: 'app_4', icon: '' },
    { id: 5, name: 'app_5', icon: '' },
    { id: 6, name: 'app_6', icon: '' },
    { id: 7, name: 'app_7', icon: '' },
    { id: 8, name: 'app_8', icon: '' },
    { id: 9, name: 'app_9', icon: '' },
    { id: 10, name: 'app_10', icon: '' },
    { id: 11, name: 'app_11', icon: '' },
    { id: 12, name: 'app_12', icon: '' },
    { id: 13, name: 'app_13', icon: '' },
    { id: 14, name: 'app_14', icon: '' },
    { id: 15, name: 'app_15', icon: '' },
    { id: 16, name: 'app_16', icon: '' },
    { id: 17, name: 'app_17', icon: '' },
    { id: 18, name: 'app_18', icon: '' },
    { id: 19, name: 'app_19', icon: '' },
    { id: 20, name: 'app_20', icon: '' },
    { id: 21, name: 'app_21', icon: '' },
    { id: 22, name: 'app_22', icon: '' },
    { id: 23, name: 'app_23', icon: '' },
    { id: 24, name: 'app_24', icon: '' },
    { id: 25, name: 'app_25', icon: '' },
    { id: 26, name: 'app_26', icon: '' },
    { id: 27, name: 'app_27', icon: '' },
    { id: 28, name: 'app_28', icon: '' },
    { id: 29, name: 'app_29', icon: '' },
    { id: 30, name: 'app_30', icon: '' },
    { id: 31, name: 'app_31', icon: '' },
    { id: 32, name: 'app_32', icon: '' },
    { id: 33, name: 'app_33', icon: '' },
    { id: 34, name: 'app_34', icon: '' },
    { id: 35, name: 'app_35', icon: '' },
    { id: 36, name: 'app_36', icon: '' },
    { id: 37, name: 'app_37', icon: '' },
    { id: 38, name: 'app_38', icon: '' },
    { id: 39, name: 'app_39', icon: '' },
    { id: 40, name: 'app_40', icon: '' },
    { id: 41, name: 'app_41', icon: '' },
    { id: 42, name: 'app_42', icon: '' },
    { id: 43, name: 'app_43', icon: '' },
    { id: 44, name: 'app_44', icon: '' },
    { id: 45, name: 'app_45', icon: '' },
    { id: 46, name: 'app_46', icon: '' },
    { id: 47, name: 'app_47', icon: '' },
    { id: 48, name: 'app_48', icon: '' },
    { id: 49, name: 'app_49', icon: '' },
    { id: 50, name: 'app_50', icon: '' },
    { id: 51, name: 'app_51', icon: '' },
    { id: 52, name: 'app_52', icon: '' },
    { id: 53, name: 'app_53', icon: '' },
    { id: 54, name: 'app_54', icon: '' },
    { id: 55, name: 'app_55', icon: '' },
    { id: 56, name: 'app_56', icon: '' },
    { id: 57, name: 'app_57', icon: '' },
    { id: 58, name: 'app_58', icon: '' },
    { id: 59, name: 'app_59', icon: '' },
    { id: 60, name: 'app_60', icon: '' },
    { id: 61, name: 'app_61', icon: '' },
    { id: 62, name: 'app_62', icon: '' },
    { id: 63, name: 'app_63', icon: '' },
    { id: 64, name: 'app_64', icon: '' },
    { id: 65, name: 'app_65', icon: '' },
    { id: 66, name: 'app_66', icon: '' },
];